//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbapp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Username {
            get {
                return ((string)(this["Username"]));
            }
            set {
                this["Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Remember {
            get {
                return ((bool)(this["Remember"]));
            }
            set {
                this["Remember"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=danipc;Initial Catalog=Logins;Integrated Security=True")]
        public string LoginsConnectionString {
            get {
                return ((string)(this["LoginsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=db-uk.hugintechnologies.com;Initial Catalog=UK;Persist Security Info=" +
            "True;User ID=rubrikkadmin@dkcw7an47l;Password=q4hi0Awi")]
        public string UK {
            get {
                return ((string)(this["UK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=db-nosedkfiza.hugintechnologies.com;Initial Catalog=Denmark;Persist S" +
            "ecurity Info=True;User ID=rubrikkadmin@h9o0tfu6g8;Password=ueoBzUGP&U2u")]
        public string DenmarkConnectionString {
            get {
                return ((string)(this["DenmarkConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=db-nosedkfiza.hugintechnologies.com;Initial Catalog=Denmark;Persist S" +
            "ecurity Info=True;User ID=rubrikkadmin@h9o0tfu6g8;Password=ueoBzUGP&U2u")]
        public string Denmark {
            get {
                return ((string)(this["Denmark"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=db-nosedkfiza.hugintechnologies.com;Initial Catalog=Norway;Persist Se" +
            "curity Info=True;User ID=rubrikkadmin@h9o0tfu6g8;Password=ueoBzUGP&U2u")]
        public string Norway {
            get {
                return ((string)(this["Norway"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=db-nosedkfiza.hugintechnologies.com;Initial Catalog=Sweden;Persist Se" +
            "curity Info=True;User ID=rubrikkadmin@h9o0tfu6g8;Password=ueoBzUGP&U2u")]
        public string Sweden {
            get {
                return ((string)(this["Sweden"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=db-nosedkfiza.hugintechnologies.com;Initial Catalog=Finland;Persist S" +
            "ecurity Info=True;User ID=rubrikkadmin@h9o0tfu6g8;Password=ueoBzUGP&U2u")]
        public string Finland {
            get {
                return ((string)(this["Finland"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=db-nosedkfiza.hugintechnologies.com;Initial Catalog=SouthAfrica;Persi" +
            "st Security Info=True;User ID=rubrikkadmin@h9o0tfu6g8;Password=ueoBzUGP&U2u")]
        public string SouthAfrica {
            get {
                return ((string)(this["SouthAfrica"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=db-de.hugintechnologies.com;Initial Catalog=Germany;Persist Security " +
            "Info=True;User ID=rubrikkadmin@mpl8x702z9;Password=q4hi0Awi")]
        public string Germany {
            get {
                return ((string)(this["Germany"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=db-au.hugintechnologies.com;Initial Catalog=Australia;Persist Securit" +
            "y Info=True;User ID=rubrikkadmin@ksjpmliqt4;Password=q4hi0Awi")]
        public string Australia {
            get {
                return ((string)(this["Australia"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=db-vn.hugintechnologies.com;Initial Catalog=Vietnam;Persist Security " +
            "Info=True;User ID=rubrikkadmin@keudaklyfu;Password=q4hi0Awi")]
        public string Vietnam {
            get {
                return ((string)(this["Vietnam"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=db-bd.hugintechnologies.com;Initial Catalog=Bangladesh;Persist Securi" +
            "ty Info=True;User ID=rubrikkadmin@gwxzwgqfxt;Password=q4hi0Awi")]
        public string Bangladesh {
            get {
                return ((string)(this["Bangladesh"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=db-ie.hugintechnologies.com;Initial Catalog=Ireland;Persist Security " +
            "Info=True;User ID=rubrikkadmin@xwvn9ei84e;Password=q4hi0Awi")]
        public string Ireland {
            get {
                return ((string)(this["Ireland"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=db-it.hugintechnologies.com;Initial Catalog=Italy;Persist Security In" +
            "fo=True;User ID=rubrikkadmin@v1c1hu0aph;Password=q4hi0Awi")]
        public string Italy {
            get {
                return ((string)(this["Italy"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=db-ch.hugintechnologies.com;Initial Catalog=Switzerland;Persist Secur" +
            "ity Info=True;User ID=rubrikkadmin@rwxcvol9ir;Password=q4hi0Awi")]
        public string Switzerland {
            get {
                return ((string)(this["Switzerland"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=db-ke.hugintechnologies.com;Initial Catalog=Kenya;Persist Security In" +
            "fo=True;User ID=rubrikkadmin@aie9prt7ll;Password=q4hi0Awi")]
        public string Kenya {
            get {
                return ((string)(this["Kenya"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=db-br.hugintechnologies.com;Initial Catalog=Brazil;Persist Security I" +
            "nfo=True;User ID=rubrikkadmin@f1oh4giyyx;Password=q4hi0Awi")]
        public string Brazil {
            get {
                return ((string)(this["Brazil"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=db-es.hugintechnologies.com;Initial Catalog=Spain;Persist Security In" +
            "fo=True;User ID=rubrikkadmin@kugxiothm9;Password=q4hi0Awi")]
        public string Spain {
            get {
                return ((string)(this["Spain"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=db-mx.hugintechnologies.com;Initial Catalog=Mexico;Persist Security I" +
            "nfo=True;User ID=rubrikkadmin@burvgyjhhm;Password=q4hi0Awi")]
        public string Mexico {
            get {
                return ((string)(this["Mexico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=db-at.hugintechnologies.com;Initial Catalog=Austria;Persist Security " +
            "Info=True;User ID=rubrikkadmin@ltwdd6oovi;Password=q4hi0Awi")]
        public string Austria {
            get {
                return ((string)(this["Austria"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=db-ar.hugintechnologies.com;Initial Catalog=Argentina;Persist Securit" +
            "y Info=True;User ID=rubrikkadmin@p9aq8xgvcc;Password=q4hi0Awi")]
        public string Argentina {
            get {
                return ((string)(this["Argentina"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=db-fr.hugintechnologies.com;Initial Catalog=France;Persist Security I" +
            "nfo=True;User ID=rubrikkadmin@ftv8jg8dd4;Password=q4hi0Awi")]
        public string France {
            get {
                return ((string)(this["France"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=db-pl.hugintechnologies.com;Initial Catalog=Poland;Persist Security I" +
            "nfo=True;User ID=rubrikkadmin@dt1vdkr840;Password=q4hi0Awi")]
        public string Poland {
            get {
                return ((string)(this["Poland"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=db-co.hugintechnologies.com;Initial Catalog=Colombia;Persist Security" +
            " Info=True;User ID=rubrikkadmin@h8ej5gxyx0;Password=q4hi0Awi")]
        public string Colombia {
            get {
                return ((string)(this["Colombia"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=db-in.hugintechnologies.com;Initial Catalog=India;Persist Security In" +
            "fo=True;User ID=rubrikkadmin@ke1ocsvquc;Password=q4hi0Awi")]
        public string India {
            get {
                return ((string)(this["India"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=db-tr.hugintechnologies.com;Initial Catalog=Turkey;Persist Security I" +
            "nfo=True;User ID=rubrikkadmin@txqkrxhb87;Password=q4hi0Awi")]
        public string Turkey {
            get {
                return ((string)(this["Turkey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=db-be.hugintechnologies.com;Initial Catalog=Belgium;Persist Security " +
            "Info=True;User ID=rubrikkadmin@rubbe;Password=q4hi0Awi")]
        public string Belgium {
            get {
                return ((string)(this["Belgium"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=db-ro.hugintechnologies.com;Initial Catalog=Romania;Persist Security " +
            "Info=True;User ID=rubrikkadmin@rubro;Password=q4hi0Awi")]
        public string Romania {
            get {
                return ((string)(this["Romania"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=db-cl.hugintechnologies.com;Initial Catalog=Chile;Persist Security In" +
            "fo=True;User ID=rubrikkadmin@d08bmbksqq;Password=q4hi0Awi")]
        public string Chile {
            get {
                return ((string)(this["Chile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=db-ca.hugintechnologies.com;Initial Catalog=Canada;Persist Security I" +
            "nfo=True;User ID=rubrikkadmin@sq2eaxbdss;Password=q4hi0Awi")]
        public string Canada {
            get {
                return ((string)(this["Canada"]));
            }
        }
    }
}
